#ifndef DRIVEAXISBASE_A_INT_DEF_H
#pragma once
#define DRIVEAXISBASE_A_INT_DEF_H

#define DRIVEAXISBASE_A_INT_SAFETY_CRC_SC1                       202
#define DRIVEAXISBASE_A_INT_SAFETY_CRC_SC2                       203
  
#define DRIVEAXISBASE_A_INT_SAFETY_EOL_CONFIG_CRC                106

#define DRIVEAXISBASE_A_INT_SAFETY_ERRORCODE_SC1                 210
#define DRIVEAXISBASE_A_INT_SAFETY_ERRORINFO1_SC1                211
#define DRIVEAXISBASE_A_INT_SAFETY_ERRORINFO2_SC1                212
#define DRIVEAXISBASE_A_INT_SAFETY_ERRORINFO3_SC1                213
#define DRIVEAXISBASE_A_INT_SAFETY_ERRORCODE_SC2                 214
#define DRIVEAXISBASE_A_INT_SAFETY_ERRORINFO1_SC2                215
#define DRIVEAXISBASE_A_INT_SAFETY_ERRORINFO2_SC2                216
#define DRIVEAXISBASE_A_INT_SAFETY_ERRORINFO3_SC2                217

#endif // DRIVEAXISBASE_A_INT_DEF_H
